export const INTRO_TEAMS_MINDX = [
    {
        id: 1,
        name: 'Nguyễn Trọng An',
        slug: 'nguyen-trong-an',
        username: 'trongandev',
        email: 'trongandev@gmail.com',
        quote: 'Luôn là một người đi trước một bước',
        position: 'Frontend Developer',
        description: `Có lẽ nghề giáo là nghề cao quý nhất trong các nghề cao quý, và tôi rất tự hào khi được trở thành một phần của đội ngũ giảng dạy tại MindX. Với niềm đam mê công nghệ và sự tận tâm trong việc truyền đạt kiến thức, tôi luôn cố gắng mang đến cho học viên những trải nghiệm học tập tốt nhất, giúp họ phát triển kỹ năng và tự tin bước vào thế giới công nghệ đầy thách thức.`,
        cvLink: 'https://res.cloudinary.com/dxjaiujm4/image/upload/v1764223342/CV_NGUYEN_TRONG_AN_-_Frontend_Developer_1_emm6dx.pdf',
        avatar: '/images/trongan.jpg',
        project: [
            {
                title: 'Quizzet - Học từ vựng các loại ngôn ngữ',
                description:
                    'Quizzet là một nền tảng giúp người dùng học các từ vựng thuộc nhiều ngôn ngữ khác nhau, sử dụng nhiều phương pháp học tập đa dạng như flashcards, trò chơi và bài kiểm tra để tăng cường khả năng ghi nhớ từ vựng một cách hiệu quả.',
                image: '/images/quizzet-site.png',
                websiteLink: 'https://www.quizzet.site/',
            },
            {
                title: 'Cà phim',
                description: 'Cà phim là một trang web giúp bạn xem phim giải trí miễn phí với kho phim đa dạng, cập nhật liên tục các bộ phim mới nhất',
                image: '/images/caphim.png',
                websiteLink: 'https://www.caphim.vercel.app/',
            },
        ],
        techStack: [
            'HTML',
            'CSS',
            'JavaScript',
            'TypeScript',
            'Python',
            'AntDesign',
            'ShadcnUI',
            'TailwindCSS',
            'Bootstrap',
            'JSON',
            'Firebase',
            'PostgreSQL',
            'MongoDB',
            'Redis',
            'ReactJS',
            'NextJS',
            'ViteJS',
            'Tanstack',
            'NodeJS',
            'ExpressJS',
            'NestJS',
            'Postman',
            'SocketIO',
            'JWT',
            'Clerk',
            'Vercel',
            'Github',
            'AWS',
            'Docker',
        ],
        aboutMe:
            'Tôi là một người đam mê sử dụng máy tính từ khi còn nhỏ, luôn chăm chỉ khám phá các công nghệ mới và áp dụng chúng vào các trang web. Tôi thành thạo HTML, CSS, JavaScript và ReactJS. Tôi cũng quen thuộc với NodeJS, ExpressJS và MongoDB. Tôi luôn sẵn sàng học hỏi các công nghệ mới và cải thiện kỹ năng của mình.',
        classData: {
            numberOfClassesTaught: 48,
            totalStudents: 239,
            expTeachingYears: '06/01/2023',
        },
        timelines: [
            {
                year: '8/2023',
                event: 'Nhận lớp dạy PTB03 đầu tiên',
            },
            {
                year: '09/2023',
                event: 'Nhận lớp dạy thứ 2 PTB05',
            },
            {
                year: '11/2023',
                event: 'Lần đầu tiên được làm giám khảo, chấm điểm các sản phẩm của học viên MindX',
            },
            {
                year: '11/2023',
                event: 'Tổ chức Demo cuối khóa PTB03',
            },
            {
                year: '06/2024',
                event: 'Làm mentor hướng dẫn các bạn học Robotics đi thi tại Robotics Challenge 2024 do trường Đại học Lạc Hồng kết hợp với UBTech tổ chức ',
                desc: 'Đạt giải nhì bảng B',
            },
            {
                year: '2024-2025',
                event: 'Được trải nghiệm dạy các môn học Python, GameMaker, Website, Computer Science',
            },
        ],
        certificates: [
            {
                name: 'Full-Stack Web Development',
                issuer: 'MindX Technology',
                issueDate: 'June 2023',
                credentialLink: 'https://mindx.edu.vn/',
            },
        ],
        socialLinks: {
            github: 'https://github.com/trongandev',
            facebook: 'https://facebook.com/trongandev',
            linkedin: 'https://www.linkedin.com/in/trongandev/',
        },
    },
    {
        id: 2,
        name: 'Nguyễn Hồng Nhung',
        slug: 'nguyen-hong-nhung',
        position: 'Backend NodeJS',
        description: 'Biết gõ phím từ lúc còn trong bụng mẹ',
        quote: 'Biết gõ phím từ lúc còn trong bụng mẹ',

        avatar: 'https://plus.unsplash.com/premium_photo-1739178656557-16b949fea186?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/nguyentrongan',
            facebook: 'https://facebook.com/nguyentrongan',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
    {
        id: 3,
        name: 'Nguyễn Nhật Huỳnh',
        slug: 'nguyen-nhat-huynh',
        position: 'Frontend Developer',
        description: 'Sống là phải chất, code phải lỗi đời mới nể',
        quote: 'Sống là phải chất, code phải lỗi đời mới nể',

        avatar: 'https://plus.unsplash.com/premium_photo-1739178656537-ea88ababab9b?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/nguyentrongan',
            facebook: 'https://facebook.com/nguyentrongan',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
    {
        id: 4,
        name: 'Thân Trọng Phúc',
        slug: 'than-trong-phuc',
        position: 'Frontend Developer',
        description: 'Gái gú chỉ là phù du, code mới là vĩnh cửu, là chân ái',
        quote: 'Gái gú chỉ là phù du, code mới là vĩnh cửu, là chân ái',

        avatar: 'https://plus.unsplash.com/premium_photo-1739178656495-8109a8bc4f53?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/nguyentrongan',
            facebook: 'https://facebook.com/nguyentrongan',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
    {
        id: 5,
        name: 'Trần Anh Vũ',
        slug: 'tran-anh-vu',
        position: 'Frontend Developer',
        description: 'Thôi tau già rồi bây, coi như không thấy anh đi',
        quote: 'Thôi tau già rồi bây, coi như không thấy anh đi',

        avatar: 'https://plus.unsplash.com/premium_photo-1738810454830-bb8f920b3259?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/nguyentrongan',
            facebook: 'https://facebook.com/nguyentrongan',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
    {
        id: 6,
        name: 'Nguyễn Xuân Hoàng',
        slug: 'nguyen-xuan-hoang',
        position: 'AI Engineer',
        description: 'Tài năng, đẹp trai, giàu có là những gì mô tả về tôi!',
        quote: 'Tài năng, đẹp trai, giàu có là những gì mô tả về tôi!',

        avatar: 'https://plus.unsplash.com/premium_photo-1739376473691-cdc1db244ac6?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/nguyentrongan',
            facebook: 'https://facebook.com/nguyentrongan',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
    {
        id: 6,
        name: 'Đặng Mai',
        slug: 'dang-mai',
        position: 'Machine Learning Engineer',
        description: 'Bạn biết tỉ phú Elon Musk chứ? Tôi thì không!!!',
        quote: 'Bạn biết tỉ phú Elon Musk chứ? Tôi thì không!!!',

        avatar: 'https://plus.unsplash.com/premium_photo-1739201499542-63a08724a1cd?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        socialLinks: {
            github: 'https://github.com/HoriDang10',
            facebook: 'https://www.facebook.com/horifatbear',
            linkedin: 'https://www.linkedin.com/in/maidang105/',
        },
    },
]
